_BASE_: "../Base-RCNN-C4.yaml"
PRETRAINS:
  DETECTRON2: "detectron2/coco_object_detection/R_50_C4_1x.pkl"
  WEIGHTS: "coco_object_detection/R_50_C4_1x.ckpt"
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 50