_BASE_: "../Base-RCNN-DilatedC5.yaml"
PRETRAINS:
  DETECTRON2: "detectron2/coco_object_detection/R_50_DC5_1x.pkl"
  WEIGHTS: "coco_object_detection/R_50_DC5_1x.ckpt"
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 50
