_BASE_: "../Base-RCNN-DilatedC5.yaml"
PRETRAINS:
  DETECTRON2: "detectron2/coco_object_detection/R_50_DC5_3x.pkl"
  WEIGHTS: "coco_object_detection/R_50_DC5_3x.ckpt"
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
