_BASE_: "Base-Panoptic-FPN.yaml"
PRETRAINS:
  DETECTRON2: "detectron2/coco_panoptic_segmentation/R_50_FPN_3x.pkl"
  WEIGHTS: "coco_panoptic_segmentation/R_50_FPN_3x.ckpt"
MODEL:
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
