_BASE_: "../Base-RCNN-FPN.yaml"
PRETRAINS:
  WEIGHTS: "misc/cascade_R_50_1x.ckpt"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeLCCHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
