_BASE_: "../Base-RCNN-FPN.yaml"
PRETRAINS:
  DETECTRON2: "detectron2/misc/cascade_X_152_32x8d_FPN_gn_dconv.pkl"
  WEIGHTS: "misc/cascade_X_152_32x8d_FPN_gn_dconv.ckpt"
MODEL:
  MASK_ON: True
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 152
    DEFORM_ON_PER_STAGE: [False, True, True, True]
  ROI_HEADS:
    NAME: "CascadeROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    NUM_CONV: 8
    NORM: "GN"
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  IMS_PER_GPU: 1
  STEPS: (35000, 45000)
  MAX_ITER: 50000
  BASE_LR: 0.16
TRANSFORM:
  RESIZE:
    MIN_SIZE_TRAIN: (640, 864)
    MAX_SIZE_TRAIN: 1440
