MODEL:
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  MASK_ON: True
  META_ARCHITECTURE: "SingleStageDetector"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  NECK:
    NAME: "FPN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SINGLE_STAGE_HEAD:
    NAME: "SOLOv2Head"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that SOLO uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TRANSFORM:
  RESIZE:
    MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
    USE_MINI_MASKS: False
